#!/usr/bin/env python3

import numpy as np
import tensorflow as tf

class DDPG():
    """
        Class to contain the PolicyNetwork and all parameters
    """
    def __init__(self, sizes, gamma=0.99, lr=0.001, lr_decay=0.9, lr_decay_steps=10000, mem_size=10000, saved_path=None):
        """
            function to initialise the class

            sizes is an array of [observations, hidden_size, actions] where observations is an array of 
            [observations_low, observations_high], hidden_size is the number of neurons in the hidden layer 
            and actions is an array of [actions_low, actions_high] in turn low is an array of low bounds for 
            each observation/action and high is an array of high bounds for each observation/action respectively

            gamma is the discount factor of future rewards

            lr is the learning rate of the neural network

            lr_decay is a float which is the rate at which the learning rate will decay exponentially

            lr_decay_steps is an int which is the number of time steps to decay the learning rate

            saved_path is a string of the path to the saved Actor-Critic network if one is being loaded
        """
        self.gamma = gamma
        self.lr = lr
        self.lr_decay = lr_decay
        self.n_actions = np.shape(sizes[2])[1]
        self.replay_mem = []
        self.mem_size = mem_size
        #Ornstein-Uhlenbeck noise generator
        self.noise = OrnsteinUhlenbeckNoise(mean=np.zeros(1), std_deviation=0.2 * np.ones(1))

        self.actor_net = ActorNet(sizes)
        self.critic_net = CriticNet(sizes)
        self.lr_decay_fn = tf.keras.optimizers.schedules.ExponentialDecay(self.lr, decay_steps=lr_decay_steps, decay_rate=self.lr_decay)
        self.actor_opt = tf.keras.optimizers.Adam(learning_rate=self.lr_decay_fn) #Adam optimiser is...
        self.critic_opt = tf.keras.optimizers.Adam(learning_rate=self.lr_decay_fn) #Adam optimiser is...

        self.actor_target = ActorNet(sizes)
        self.actor_target.set_weights(self.actor_net.get_weights())
        self.critic_target = CriticNet(sizes)
        self.critic_target.set_weights(self.critic_net.get_weights())

        #load a saved model (neural net) if provided
        if saved_path:
            self.actor_net = tf.keras.models.load_model(f'{saved_path}/actor_net', custom_object={"CustomModel": ActorNet})
            self.actor_target = tf.keras.models.load_model(f'{saved_path}/actor_net', custom_objects={"CustomModel": ActorNet})

            self.critic_net = tf.keras.models.load_model(f'{saved_path}/critic_net', custom_object={"CustomModel": CriticNet})
            self.critic_target = tf.keras.models.load_model(f'{saved_path}/critic_net', custom_objects={"CustomModel": CriticNet})

    def get_parameters(self):
        """
            function to get the parameters of the algorithm

            returns a dict with all the algorithm parameters
        """
        return {"gamma": self.gamma, "lr": self.lr, "lr_decay": self.lr_decay, "mem_size": self.mem_size}

    def save_model(self, path):
        """
            function to save the tensorflow model (neural net) to a file

            path is a string of the path to the file where the model will be saved
        """
        self.actor_net.save(f'{path}/actor_net')
        self.critic_net.save(f'{path}/critic_net')

    def get_action(self, obv):
        """
            function to get the action based on the current observation using the 
            policy generated by the neural net

            obv is the current observation of the state

            returns the action to take
        """
        action = self.actor_net(np.array([obv])).numpy()[0]            
        #add noise for exploration
        action += self.noise()

        return action

    def store_step(self, obv, action, reward, next_obv):
        """
            function to store an step's tuple of values

            obv is the observation of the current state

            action is an int of the action taken

            reward is the reward returned when the action is applied to the current state

            next obv is the observation of the next state after action has been applied to the current state
            (placeholder for compatibility across algorithm classes)
        """
        #appends dictionary of step tuple to replay memory
        self.replay_mem.append({"obv": obv, "action": action, "reward": reward, "next_obv": next_obv})

        #if replay memory is greater than maximum size then remove oldest step
        if len(self.replay_mem) > self.mem_size:
            self.replay_mem.pop(0)

    def train(self, batch_size):
        """
            function to train Policy network using previous episode data from replay memory

            batch size is the number of experiences to train the Q-network with

            returns the loss of the training as a tensor
        """
        indices = np.random.choice(range(len(self.replay_mem)), size=batch_size)

        #samples of each piece of data from a random step in replay memory
        obv_batch = np.array([self.replay_mem[i]["obv"] for i in indices], dtype=np.float32)
        action_batch = np.array([self.replay_mem[i]["action"] for i in indices])
        reward_batch = np.array([self.replay_mem[i]["reward"] for i in indices], dtype=np.float32)
        next_obv_batch = np.array([self.replay_mem[i]["next_obv"] for i in indices], dtype=np.float32)

        actor_targets = self.actor_target(next_obv_batch)
        critic_targets = self.critic_target(next_obv_batch, actor_targets)
        #calculate expected reward for each sample
        critic_targets = reward_batch + self.gamma * critic_targets

        #backpropagation for critic network
        with tf.GradientTape() as tape:
            values = self.critic_net(obv_batch, action_batch)
            critic_loss = tf.reduce_mean(tf.square(critic_targets - values)) 
        
        critic_grads = tape.gradient(critic_loss, self.critic_net.trainable_variables)
        self.critic_opt.apply_gradients(zip(critic_grads, self.critic_net.trainable_variables))

        #backpropagation for actor network using updated critic network
        with tf.GradientTape() as tape:
            actions = self.actor_net(obv_batch)
            values = self.critic_net(obv_batch, actions)
            actor_loss = -tf.reduce_mean(values)

        actor_grads = tape.gradient(actor_loss, self.actor_net.trainable_variables)
        self.actor_opt.apply_gradients(zip(actor_grads, self.actor_net.trainable_variables))

        return actor_loss + critic_loss

    def update_target_net(self):
        """
            function to update the weights of the target network
        """
        self.actor_target.set_weights(self.actor_net.get_weights())
        self.critic_target.set_weights(self.critic_net.get_weights())

class ActorNet(tf.keras.Model):
    """
        Class to contain the neural network approximating the policy (actor) and Q-value function (critic)
    """
    def __init__(self, sizes):
        """
            function to initialise the class

            sizes is an array of [observations, hidden_size, actions] where observations is an array of 
            [observations_low, observations_high], hidden_size is the number of neurons in the hidden layer 
            and actions is an array of [actions_low, actions_high] in turn low is an array of low bounds for 
            each observation/action and high is an array of high bounds for each observation/action respectively

            continuous is a bool to determine if the action space is continuous
        """
        super(ActorNet, self).__init__()

        #init to between -0.003 and 0.003 to prevent an output of -1 or 1 from the tanh output layer
        k_init = tf.random_uniform_initializer(minval=-0.003, maxval=0.003)

        self.hidden1 = tf.keras.layers.Dense(np.shape(sizes[0])[1], activation="relu")
        self.hidden2 = tf.keras.layers.Dense(sizes[1], activation="relu")
    
        #continuous action space outputs tanh from net to provide value for each action    
        self.actor = tf.keras.layers.Dense(np.shape(sizes[2])[1], activation="tanh", kernel_initializer=k_init)

        #scaler for bounds of action space
        self.scaler = sizes[2][1] - sizes[2][0]

    def call(self, obv):
        """
            function to define the forward pass of the neural network this function is called 
            when QNet(inputs) is called or QNet.predict(inputs) is called

            obv is the numpy array or tensor of the inputs values to the neural network

            returns a tensor of the probability distribution of the policy output by the neural network
        """
        obv = self.hidden1(obv)
        obv = self.hidden2(obv)
        #multiply output by scaler to keep within bounds of action space
        policy = self.actor(obv) * self.scaler

        return policy

class CriticNet(tf.keras.Model):
    """
        Class to contain the neural network approximating the policy (actor) and Q-value function (critic)
    """
    def __init__(self, sizes):
        """
            function to initialise the class

            sizes is an array of [observations, hidden_size, actions] where observations is an array of 
            [observations_low, observations_high], hidden_size is the number of neurons in the hidden layer 
            and actions is an array of [actions_low, actions_high] in turn low is an array of low bounds for 
            each observation/action and high is an array of high bounds for each observation/action respectively

            continuous is a bool to determine if the action space is continuous
        """
        super(CriticNet, self).__init__()
        self.obv_hidden1 = tf.keras.layers.Dense(np.shape(sizes[0])[1], activation="relu")
        self.action_hidden1 = tf.keras.layers.Dense(np.shape(sizes[2])[1], activation="relu")

        self.concatenate = tf.keras.layers.Concatenate()

        self.hidden2 = tf.keras.layers.Dense(sizes[1], activation="relu")
        self.critic = tf.keras.layers.Dense(1, activation="linear")

    def call(self, obv, action):
        """
            function to define the forward pass of the neural network this function is called 
            when QNet(inputs) is called or QNet.predict(inputs) is called

            obv is the numpy array or tensor of the inputs values to the neural network

            action is the action taken for that observation as output by the actor network

            returns a tensor of the probability distribution of the policy output by the neural network
        """
        obv = self.obv_hidden1(obv)
        action = self.action_hidden1(action)

        obv_action = self.concatenate([obv, action])

        obv_action = self.hidden2(obv_action)
        value = self.critic(obv_action)

        return value

class OrnsteinUhlenbeckNoise():
    """
        Class to generate Ornstein-Uhlenbeck noise
    """
    def __init__(self, mean, std_deviation, theta=0.15, dt=1e-2, x_initial=None):
        self.theta = theta
        self.mean = mean
        self.std_dev = std_deviation
        self.dt = dt
        self.x_initial = x_initial
        self.reset()

    def __call__(self):
        # Formula taken from https://www.wikipedia.org/wiki/Ornstein-Uhlenbeck_process.
        x = (
            self.x_prev
            + self.theta * (self.mean - self.x_prev) * self.dt
            + self.std_dev * np.sqrt(self.dt) * np.random.normal(size=self.mean.shape)
        )
        # Store x into x_prev
        # Makes next noise dependent on current one
        self.x_prev = x

        return x

    def reset(self):
        if self.x_initial is not None:
            self.x_prev = self.x_initial
        else:
            self.x_prev = np.zeros_like(self.mean)


